#!/usr/bin/env python

import sys

with open('demo-leaflet/protomaps_rs.js','r') as f:
    lines = list(f.readlines())[0:-2]

with open('lib.js','r') as f:
    lib = list(f.readlines())[1:]
    lines = lines + lib

for l in lines:
    print(l,end='')

